<?php

namespace DonationBundle\Repository;

/**
 * factureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class factureRepository extends \Doctrine\ORM\EntityRepository
{

    public function findiddonation($id)
    {
        $query=$this->getEntityManager()->createQuery("SELECT donationid FROM DonationBundle:facture f where f.donationid=:id ")
            ->setParameter('id', $id);
        return $query->getResult();
    }
    public function findfacture($id) {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('u')
            ->from($this->_entityName, 'u')
            ->where('u.donation_id LIKE :id')
            ->setParameters([
                'id' => $id
            ]);
        return $qb->getQuery()->getResult();
    }
}
