<?php

namespace GroupeBundle\Repository;

/**
 * TopicsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TopicsRepository extends \Doctrine\ORM\EntityRepository
{
}
