ajouter:
    path:     /ajouter
    defaults: { _controller: evenementBundle:evenement:new }
afficher:
    path:     /afficherchasseur
    defaults: { _controller: evenementBundle:evenement:afficher }
supprimer:
    path:     /supprimer/{id}
    defaults: { _controller: evenementBundle:evenement:supprimer }
modifier:
    path:     /modifier/{id}
    defaults: { _controller: evenementBundle:evenement:modifier }
afficheruser:
    path:     /afficheruser
    defaults: { _controller: evenementBundle:evenement:afficheruser }
ajouterticket:
    path:     /ajouterticket/{id}
    defaults: { _controller: evenementBundle:ticket:ajouterticket }
afficheruser1:
    path:     /afficheruser1/{id}
    defaults: { _controller: evenementBundle:evenement:afficheruser1 }
supprimerticket:
    path:     /supprimerticket/{id}
    defaults: { _controller: evenementBundle:ticket:supprimerticket }
consulterticket:
    path:     /consulterticket/{id}
    defaults: { _controller: evenementBundle:ticket:consulterticket }
afficherchasseur:
    path:     /afficherchasseur
    defaults: { _controller: evenementBundle:evenement:afficher }
afficherevenementAdmin:
    path:     /admin/afficherAdmin
    defaults: { _controller: evenementBundle:evenement:afficherevenementAdmin }
supprimerAdmin:
    path:     /admin/supprimerAdmin/{id}
    defaults: { _controller: evenementBundle:evenement:supprimerAdmin }
detailevenementadmin:
    path:     /admin/detailevenementadmin/{id}
    defaults: { _controller: evenementBundle:evenement:detailevenementadmin }
pdf:
    path:     /pdf/{id}
    defaults: { _controller: evenementBundle:ticket:pdf }
supprimerparticipe:
    path:     /supprimerparticipe/{id}
    defaults: { _controller: evenementBundle:ticket:supprimerticket }
detailuser:
    path:     /detailuser/{id}
    defaults: { _controller: evenementBundle:evenement:detailuser }
ajax_search:
    path:     /admin/search
    defaults: { _controller: evenementBundle:evenement:search }
_graphePie:
    path:     /admin/pie
    defaults: { _controller: evenementBundle:evenement:pie}
