<?php

namespace DonationBundle\Repository;

/**
 * donationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class donationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findday()
    {
        $date= new \DateTime("now");
        $query=$this->getEntityManager()->createQuery("SELECT t FROM DonationBundle:donation t where t.dateCr = :date ")
            ->setParameter('date', $date->format('Y-m-d'));
        return $query->getResult();
    }
}
