<?php

namespace DonationBundle\Repository;

/**
 * donationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class donationRepository extends \Doctrine\ORM\EntityRepository
{

}
