<?php

namespace FOSBundle\Repository;

/**
 * chasseurtalentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class chasseurtalentRepository extends \Doctrine\ORM\EntityRepository
{
}
