<?php

namespace FOSBundle\Repository;

/**
 * talentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class talentRepository extends \Doctrine\ORM\EntityRepository
{
}
