sponsors_homepage:
    path:     /
    defaults: { _controller: SponsorsBundle:Default:index }



pack_new:
    path:     /pack/new
    defaults: { _controller: SponsorsBundle:Pack:new }

pack_index:
    path:     /pack
    defaults: { _controller: SponsorsBundle:Pack:index }

pack_show:
    path:     /pack/show/{idad}
    defaults: { _controller: SponsorsBundle:Pack:show }

pack_edit:
    path:     /pack/edit/{idad}
    defaults: { _controller: SponsorsBundle:Pack:edit }

pack_delete:
    path:     /pack/delete/{idad}
    defaults: { _controller: SponsorsBundle:Pack:delete }


sponsor_new:
    path:     /sponsor/new
    defaults: { _controller: SponsorsBundle:Sponsor:new }

sponsor_index:
    path:     /sponsor
    defaults: { _controller: SponsorsBundle:Sponsor:index }

sponsor_user_index:
    path:     /sponsor/user
    defaults: { _controller: SponsorsBundle:Sponsor:user_index }

sponsor_show:
    path:     /sponsor/show/{idsp}
    defaults: { _controller: SponsorsBundle:Sponsor:show }

sponsor_user_show:
    path:     /sponsor/user/show/{idsp}
    defaults: { _controller: SponsorsBundle:Sponsor:user_show }

sponsor_edit:
    path:     /sponsor/edit/{idsp}
    defaults: { _controller: SponsorsBundle:Sponsor:edit }
sponsor_delete:
    path:     /sponsor/delete/{idsp}
    defaults: { _controller: SponsorsBundle:Sponsor:delete }

