<?php

namespace SponsorsBundle\Repository;

/**
 * MailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MailRepository extends \Doctrine\ORM\EntityRepository
{
    public function  findUserMailsQB($idu){

        $query=$this->getEntityManager()
            ->createQuery("SELECT m FROM SponsorsBundle:Mail m WHERE m.idu =:idu")
            ->setParameter('idu',$idu);
        return $query->getResult();
    }
    public function  findMailsQB($idu,$subject){
        $query=$this->getEntityManager()
            ->createQuery("SELECT m FROM SponsorsBundle:Mail m WHERE m.idu=:idu and  m.subject like :sub")
            ->setParameters(['idu'=>$idu, 'sub'=>'%'.$subject.'%']);
        return $query->getResult();
    }
}
