<?php

namespace SponsorsBundle\Repository;

use Symfony\Component\Validator\Constraints\Date;

/**
 * PackRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PackRepository extends \Doctrine\ORM\EntityRepository
{
    public function sumQB(){
        $query=$this->getEntityManager()
            ->createQuery("SELECT sum(p.price) FROM SponsorsBundle:Pack p ");

        return $query->getSingleScalarResult();
    }
    public function packsQB(){
        $query=$this->getEntityManager()
            ->createQuery("SELECT count(p) FROM SponsorsBundle:Pack p ");

        return $query->getSingleScalarResult();
    }
    public function  adsLeftQB(){

        $query=$this->getEntityManager()
            ->createQuery("SELECT count(p) FROM SponsorsBundle:Pack p WHERE p.position =:pos")
            ->setParameter('pos','Left');
        return $query->getSingleScalarResult();
    }
    public function  adsRightQB(){

        $query=$this->getEntityManager()
            ->createQuery("SELECT count(p) FROM SponsorsBundle:Pack p WHERE p.position =:pos")
            ->setParameter('pos','Right');
        return $query->getSingleScalarResult();
    }

    public function  editCurrentAdQB(){

        $query=$this->getEntityManager()
            ->createQuery("UPDATE SponsorsBundle:Pack p SET p.status=:stat WHERE CURRENT_DATE() BETWEEN p.displaydate AND p.discarddate")
            ->setParameter(':stat','Displaying')
            ->execute();

    }
    public function  editHistoryAdQB(){

        $query=$this->getEntityManager()
            ->createQuery("UPDATE SponsorsBundle:Pack p SET p.status=:stat WHERE CURRENT_DATE() > p.discarddate")
            ->setParameter(':stat','History')
            ->execute();

    }
    public function  editProgAdQB(){

        $query=$this->getEntityManager()
            ->createQuery("UPDATE SponsorsBundle:Pack p SET p.status=:stat WHERE CURRENT_DATE() < p.displaydate")
            ->setParameter(':stat','Programmed')
            ->execute();

    }
    public function  pubparsponsorQB(){

        $query=$this->getEntityManager()
            ->createQuery("SELECT  s.namesp, count(p) as pubnb FROM SponsorsBundle:Sponsor s, SponsorsBundle:Pack p WHERE s.idsp =p.idsp group by s.namesp order by pubnb desc ");
        $query->setMaxResults(3);
        return $query->getResult();
    }

    public function  maxpQB(){

        $query=$this->getEntityManager()
            ->createQuery("SELECT max(p.price) as pubnb FROM SponsorsBundle:Sponsor s, SponsorsBundle:Pack p WHERE s.idsp =p.idsp group by s.namesp ");

        return $query->getSingleScalarResult();
    }

    public function  ad1QB()
    {
        $query=$this->getEntityManager()
            ->createQuery("SELECT p.ad as pub FROM  SponsorsBundle:Pack p order by pub desc ");
        $query->setMaxResults(3);
        return $query->getResult();

    }
    public function  ad2QB()
    {
        $query=$this->getEntityManager()
            ->createQuery("SELECT p.ad as pub FROM  SponsorsBundle:Pack p order by pub asc ");
        $query->setMaxResults(3);
        return $query->getResult();

    }
}
