<?php

namespace SponsorsBundle\Repository;

/**
 * SponsorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SponsorRepository extends \Doctrine\ORM\EntityRepository
{
    public function  spQB(){

        $query=$this->getEntityManager()
            ->createQuery("SELECT count(p) FROM SponsorsBundle:Sponsor p ");

        return $query->getSingleScalarResult();
    }
}
