<?php

namespace SponsorsBundle\Repository;

/**
 * MailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MailRepository extends \Doctrine\ORM\EntityRepository
{
    public function  idspQB($email){

        $query=$this->getEntityManager()
            ->createQuery("SELECT s.idsp FROM SponsorsBundle:Sponsor s WHERE s.email =:em")
            ->setParameter('em',$email);
        return $query->getSingleScalarResult();
    }
}
