donation_index2:
  path:     /
  defaults: { _controller: "DonationBundle:donation:index2" }
  methods:  GET

donation_edit2:
  path:     /{id}/edit
  defaults: { _controller: "DonationBundle:donation:edit2" }
  methods:  [GET, POST]


donation_delete2:
  path:     /{id}/delete
  defaults: { _controller: "DonationBundle:donation:delete2" }

