facture_index:
    path:     /
    defaults: { _controller: "DonationBundle:facture:index" }
    methods:  GET
facture_noti:
    path:     /{id}/noti
    defaults: { _controller: "DonationBundle:facture:Notif" }
    methods:  GET
facture_pdf:
    path:     /{id}/pdf
    defaults: { _controller: "DonationBundle:facture:pdf" }
facture_pdf2:
    path:     /pdf2
    defaults: { _controller: "DonationBundle:facture:pdf2" }

facture_show:
    path:     /{id}/show
    defaults: { _controller: "DonationBundle:facture:show" }
    methods:  GET

facture_new:
    path:     /{id}/new
    defaults: { _controller: "DonationBundle:facture:new" }
    methods:  [GET, POST]

facture_edit:
    path:     /{id}/edit
    defaults: { _controller: "DonationBundle:facture:edit" }
    methods:  [GET, POST]

facture_delete:
    path:     /{id}/delete
    defaults: { _controller: "DonationBundle:facture:delete" }
    methods:  DELETE
