<?php

namespace evenementBundle\Repository;

/**
 * evenementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class evenementRepository extends \Doctrine\ORM\EntityRepository
{

    public function Deleteevenement($id){
        $query = $this->getEntityManager()
            ->createQuery("DELETE evenementBundle:evenement e
          where e.evenement=:id")->setParameter('id', $id);


        return $query->getResult();
    }
}
