topics_index:
    path:     /
    defaults: { _controller: "GroupeBundle:Topics:index" }
    methods:  GET

topics_show:
    path:     /topics/{id}/show
    defaults: { _controller: "GroupeBundle:Topics:show" }
    methods:  GET

topics_new:
    path:     /topics/new
    defaults: { _controller: "GroupeBundle:Topics:new" }
    methods:  [GET, POST]

topics_edit:
    path:     /topics/{id}/edit
    defaults: { _controller: "GroupeBundle:Topics:edit" }
    methods:  [GET, POST]

topics_delete:
    path:     /topics/{id}/delete
    defaults: { _controller: "GroupeBundle:Topics:delete" }
    methods:  DELETE
